language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

script: phpunit --coverage-clover=coverage.clover